<?php
/*************************************************************************
 * Sparky
 * https://github.com/writersky/Sparky
 * Copyright 2013 Writersky.
 *
 * Licensed under the The GNU Lesser General Public License,
 * version 2.1 (LGPL-2.1).
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://opensource.org/licenses/lgpl-2.1.php
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **************************************************************************
 * Controller layer for phpMailer. This can be modifier if phpMailer is 
 * not the SMTP library you use. 
 *                                                                      
 * @author  Harris Wong                                                 
 * @date    Mar 25th, 2013                                              
 *************************************************************************/
class MailerManager extends PHPMailer {
    function __construct() {
        //Setup config
        $this->IsSMTP(); // enable SMTP
        $this->SMTPDebug = 1;  // debugging: 1 = errors and messages, 2 = messages only
        $this->SMTPAuth = true;  // authentication enabled
        //$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
        $this->Host = MAILER_HOST;
        $this->Port = MAILER_PORT; 
        $this->Username = MAILER_USERNAME;  
        $this->Password = MAILER_PASSWORD;
    }

    /**
     * Sends an email with a custom email and name. Currently used by contact-us page.
     *
     * @param   String      $to             Recipient's email
     * @param   String      $from           Sender's email
     * @param   String      $from_name      Sender's name appears on email 
     * @param   String      $subject        Email Subject
     * @param   String      $body           Email message body
     * @todo    Support HTML/plain text.
     */
    function smtpmailer($to, $from, $from_name, $subject, $body) { 
        global $_messages;

        try {
            $this->SetFrom($from, $from_name);
            $this->Subject = $subject;
            //$body = $body . $this->getSignature($userObject->get_email());
            $this->Body = $body;
            $this->AddAddress($to);
            parent::Send();
        } catch (phpmailerException $e) {
            $_messages->SetError($e->errorMessage());
        }
    }
    
    /**
     * Retrieve the signature for this mailer
     */
    function getSignature($email) {
        $signature = "\n\n=======================================
This is an automated message generated by www.writersky.com.\n";
        return $signature;
    }
}
?>