#!/bin/sh

#/*************************************************************************
# * Sparky
# * https://github.com/writersky/Sparky
# * Copyright 2013 Writersky.
# *
# * Licensed under the The GNU Lesser General Public License,
# * version 2.1 (LGPL-2.1).
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# * http://opensource.org/licenses/lgpl-2.1.php
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# **************************************************************************
# * Parse get yesterday log and dump them into a log file.
# * USAGE: 
# *     Change server log:
# *             "/path/to/your/server_log/error.log" to ie.
# *             "/var/log/error.log"
# *     Change sparky folder:
# *             "/path/to/your/sparky_folder/" to ie.
# *             "/usr/script/sparky/"
# *                                                                      
# * @author  Harris Wong                                                 
# * @date    Mar 25th, 2013                                              
# *************************************************************************/
 
grep "$(date -d'now-1 day' +'%a %b %d ')" /path/to/your/server_log/error.log > /path/to/your/sparky_folder/sparky_log.txt;
php /path/to/your/sparky_folder/Sparky.php;
rm /path/to/your/sparky_folder/sparky_log.txt;
